name = "CategoricalPopulationDynamics"
uuid = "04a5e6ed-5bdd-4eeb-ad4c-515b60df3359"
version = "0.1.0"
authors = ["Simon Frost"]

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StructuredPopulationCore = "33358fd2-7d60-4541-bded-caea801370e0"

[weakdeps]
ContinuousStatePopulationDynamics = "5a68bfab-dffa-4d3c-8723-3d784ca1a3c3"
FiniteStatePopulationDynamics = "c910fb8b-fb88-47fe-a579-bc7a7e1444df"
IntegralProjectionModels = "00376763-44f4-49c9-a075-cdcba60854bb"
MatrixProjectionModels = "521f12cc-5854-454d-93a2-8be28ae7cee2"

[extensions]
CategoricalPopulationDynamicsContinuousStatePopulationDynamicsExt = "ContinuousStatePopulationDynamics"
CategoricalPopulationDynamicsFiniteStatePopulationDynamicsExt = "FiniteStatePopulationDynamics"
CategoricalPopulationDynamicsIPMExt = "IntegralProjectionModels"
CategoricalPopulationDynamicsMPMExt = "MatrixProjectionModels"

[sources]
ContinuousStatePopulationDynamics = {path = "../ContinuousStatePopulationDynamics.jl"}
FiniteStatePopulationDynamics = {path = "../FiniteStatePopulationDynamics.jl"}
IntegralProjectionModels = {path = "../IntegralProjectionModels.jl"}
MatrixProjectionModels = {path = "../MatrixProjectionModels.jl"}
StructuredPopulationCore = {path = "../StructuredPopulationCore.jl"}

[compat]
Catlab = "0.17"
ContinuousStatePopulationDynamics = "0.1.0"
FiniteStatePopulationDynamics = "0.1.0"
IntegralProjectionModels = "0.1.0"
LinearAlgebra = "1"
MatrixProjectionModels = "0.1.0"
Plots = "1"
julia = "1.10"

[extras]
ContinuousStatePopulationDynamics = "5a68bfab-dffa-4d3c-8723-3d784ca1a3c3"
FiniteStatePopulationDynamics = "c910fb8b-fb88-47fe-a579-bc7a7e1444df"
IntegralProjectionModels = "00376763-44f4-49c9-a075-cdcba60854bb"
MatrixProjectionModels = "521f12cc-5854-454d-93a2-8be28ae7cee2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "IntegralProjectionModels", "ContinuousStatePopulationDynamics", "FiniteStatePopulationDynamics", "MatrixProjectionModels"]
